<<<<<<< HEAD
apiKey: 
authDomain: 
databaseURL: 
projectId: 
storageBucket: 
messagingSenderId: 
<<<<<<< HEAD
appId: 
=======
appId: 
=======
apiKey:
authDomain:
databaseURL:
projectId:
storageBucket:
messagingSenderId:
appId:
>>>>>>> a0363bd11104736cf72987457f35971b35c18d2a
>>>>>>> main
